//Guessing game : Guess the number generated by computer mutliple times.
import java.util.Scanner;

public class guess {

    public static void main(String[] args) {
        
        int guess = 0;
        int count =0;
        final Scanner input = new Scanner(System.in);
       

        //Generate a random number between 1 and 100.
        final int randnum = (int) (Math.random() * 100 + 1);

        while( guess != randnum){

        System.out.println("Enter a nuber between 1 and 100 : ");
        guess = input.nextInt();

        if (guess < randnum){
            System.out.println("Higher");
        }
        else if(guess > randnum){
            System.out.println("Lower");
        }
        else {
            System.out.println("You get it!!");
            break;
        }
        count++;
    }
    //End While loop
    input.close();
    System.out.println("You took " + count + "steps to guess the number.");
    }
}