//Guessing game : Guess the number generated by computer only once.
import java.util.Scanner;

public class guessIf {

    public static void main(String[] args) {
        
        int guess = 0;
        final Scanner input = new Scanner(System.in);
        System.out.println("Enter a nuber between 1 and 100 : ");
        guess = input.nextInt();

        //Generate a random number between 1 and 100.
        final int randnum = (int) (Math.random() * 100 + 1);

        if (guess < randnum){
            System.out.println("Sorry!You don't get it.");
        }
        else if(guess > randnum){
            System.out.println("Sorry!You don't get it.");
        }
        else {
            System.out.println("You get it!!");
        }
    }
}